#######
POST http://{{web-server}}/parse/auchan/cataloglinks/
Content-Type: text/html
#######

POST http://{{web-server}}/parse/auchan/cataloglinks/sport-i-otdyh/
Content-Type: text/html
#######

GET http://{{web-server}}/parse/auchan/cataloglinks