#######
POST http://localhost:8080/parse/auchan/cataloglinks/
Content-Type: text/html
#######

POST http://localhost:8080/parse/auchan/cataloglinks/sport-i-otdyh/
Content-Type: text/html
#######

GET http://localhost:8080/parse/auchan/cataloglinks